INSERT INTO TB_CATEGORY (NAME) VALUES ('Books');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Movies');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Forense');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Eletronics');